# Generated by Django 3.1.5 on 2021-08-15 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Talks',
            fields=[
                ('talk_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('confirmed_by_to', models.BooleanField(default=False)),
                ('confirmed_by_from', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fid', to=settings.AUTH_USER_MODEL)),
                ('to_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('from_user_id', models.IntegerField(null=True)),
                ('content', models.CharField(max_length=500)),
                ('talk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postapp.talks')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('favorite_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('talk_id', models.IntegerField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
