# Generated by Django 3.1.5 on 2021-07-22 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_message_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_at',
        ),
        migrations.AddField(
            model_name='talks',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
