# Generated by Django 3.1.5 on 2021-08-16 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_auto_20210816_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='talk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postapp.talks'),
        ),
    ]
