# Generated by Django 3.1.5 on 2021-08-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0003_auto_20210816_1336'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.UniqueConstraint(fields=('user_id', 'talk_id'), name='favorite_unique'),
        ),
    ]
